trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Azure Function'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
    - script: |
        dotnet restore
        dotnet build --configuration Release
      displayName: 'Build the Azure Function App'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: |
        dotnet test --configuration Release
      displayName: 'Run Unit Tests'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Simulated Deploy Step'
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo "Manual deploy will be handled using Azure CLI."
      displayName: 'Deploy placeholder'
